### ISSUE TITLE
PlutoColumnType.select don't update value in release mode

### ISSUE THREAD

**Issue by baryalenn** [doonfrs/pluto_grid_plus#21]
When I select an object (instance of PersonModel) in the list it does not update the value in the cell in release mode, however it works in debug mode.

### Code sample
```dart
PlutoColumn(
  title: 'Person',
  field: personField,
  width: 120,
  type: PlutoColumnType.select(listPerson), // listPerson is List of PersonModel
  applyFormatterInEditing: true,
  formatter: (dynamic value) {
	// value is instance of PersonModel
	return value == null || value == "" ? "" : "${value?.lastName ?? "?"} ${value?.firstName ?? "?"}";
  }),
```

### Execution Environment
**Flutter version**
Flutter version is 3.16.5

**PlutoGrid version**
PlutoGrid version is 7.0.2

**OS**
Windows 11

**Comment by doonfrs** [comment]
PlutoGrid version is 7.0.2

I couldn't expect the reason behind the bug, but I found that you are using pluto_grid, you need to move to pluto_grid_plus and use the latest version from pub.dev, then give it a try, because the old version is not supported anymore.
please consider checking the debug console in Chrome maybe something is wrong is happening.
